apps/fabric8-mq/pom.xml
apps/fabric8-mq/src/main/java/io/fabric8/mq/Main.java
apps/fabric8-mq/src/test/java/io/fabric8/mq/MqttConnectorTest.java

Hi,
Now it is possible to start broker with the MQTT connector:
docker run -p 1883:1883 -e AMQ_MQTT_PORT=1883 -it dockerhost:5000/fabric8/fabric8-mq:2.1-SNAPSHOT
IMHO we should add similar options for AMQP, STOMP and other AMQ transports.
Cheers.

Added optional MQTT connector to the fabric8-mq

---

apps/fabric8-mq-autoscaler/build-and-run.sh
apps/fabric8-mq-autoscaler/push.sh
apps/fabric8-mq-consumer/build-push-deploy.sh
apps/fabric8-mq-consumer/build-push-run.sh
apps/fabric8-mq-consumer/push.sh
apps/fabric8-mq-producer/build-push-deploy.sh
apps/fabric8-mq-producer/build-push-run.sh
apps/fabric8-mq-producer/push.sh
apps/fabric8-mq/build-push-deploy.sh
apps/fabric8-mq/build-push-run.sh

ActiveMQ projects are on 2.2-SNAPSHOT, but bash scripts still refer to 2.0-SNAPSHOT

Fixed version numbers in activemq app bash scripts

---

quickstarts/java/pom.xml

lets disable the jgroups quickstart for now so that the release can go through while we figure out the docker release issues

lets disable the jgroups quickstart for now so that the release can go through while we figure out the docker release issues

---

apps/apiman/pom.xml
apps/apiman/src/main/docker/Dockerfile

Note that the jube image should be renamed to jboss/wildfly to be consistent with the docker naming.

Setting correct ownership for the wildfly files

---

apps/jenkins/src/main/fabric8/kubernetes.json

There is a new ruby-20 image(ruby-20-centos7) and we are going to get rid of the old one(ruby-20-centos)

Updating image name to new ruby-20-centos7

---

apps/fabric8-forge/pom.xml

avoid cert errors when trying to use the kube REST API inside the fabric8 forge pod

avoid cert errors when trying to use the kube REST API inside the fabric8 forge pod

---

apps/gogs/pom.xml

disable https on gogs for now until we've a valid cert so that STI and Orion can clone from https on gogs

disable https on gogs for now until we've a valid cert so that STI and Orion can clone from https on gogs

---

apps/gogs/pom.xml

use port 80 for gogs for now so it matches the http protocol

use port 80 for gogs for now so it matches the http protocol

---

apps/jenkins/src/main/fabric8/kubernetes.json

switch to use the new fabric8 jenkins image which comes with out of the box maven integration

switch to use the new fabric8 jenkins image which comes with out of the box maven integration

---

app-groups/base/pom.xml

app library is now not really needed for the console as we can use templates instead now

app library is now not really needed for the console as we can use templates instead now

---

app-groups/cdelivery-core/pom.xml

As the new Fabric8 docker gerrit image has been tested successfully like also the gerrit kube app, we can add it to the cdelivery-core app

Include gerrit kube app

---

apps/gerrit/src/main/fabric8/env.properties
apps/gerrit/src/main/java/io/fabric8/app/gerrit/GerritModelProcessor.java

Adopt same convention as other services to call internally the containers. 
- So let's remove -service from gerrit-http and gerrit-ssh service names.
- Rename the internal hostname of the gogs-http server to allow the replication to work

Adopt same convention as other services to call internally the containers

---

apps/gerrit/src/main/fabric8/env.properties

Since openshift 0.5.3, openshift has changed the internal domain name to be used to query a pod running within the namespace
They change `<service>.<namespace>.local` to `<service>.<namespace>.svc.cluster.local`. By consequence the env property `GIT_SERVER_IP` must be changed to `gogs-http.default.svc.cluster.local`.

Change server hostname as openshift has changed the internal domain name

---

apps/gerrit/pom.xml
apps/gerrit/src/main/fabric8/env.properties
apps/gerrit/src/main/java/io/fabric8/app/gerrit/GerritModelProcessor.java

Update gerrit kube app to support new fabric8/docker image (env vars / volumes) :
* Add missing env vars (create-user-plugin, java-job changing the permissions)
* Define the volumes (keys to be imported)
* Change link to gogs service & not anymore gogs-http
* Change gerrit-http service to gerrit service

Update Kube App to support the new Docker Gerrit Image

---

apps/fabric8mq-autoscaler/src/main/java/io/fabric8/mq/autoscaler/MQAutoScaler.java

lets delegate to the KubernetesClient and let it figure out where the master is via env vars, service discovery or the ~/.kube/config file

lets delegate to the KubernetesClient and let it figure out where the master is via env vars, service discovery or the ~/.kube/config file

---

apps/amqbroker/pom.xml
apps/api-registry/pom.xml
apps/apiman/pom.xml
apps/app-library/pom.xml
apps/cdelivery/pom.xml
apps/chaos-monkey/pom.xml
apps/fabric8-forge/pom.xml
apps/fabric8-http-gateway/pom.xml
apps/fabric8mq-autoscaler/pom.xml
apps/fabric8mq-consumer/pom.xml
apps/fabric8mq-controller/pom.xml
apps/fabric8mq-producer/pom.xml
apps/fabric8mq/pom.xml
apps/hubot-notifier/pom.xml
apps/infinispan-server/pom.xml
pom.xml

upgrade to the latest docker plugin version and use a docker prefix which seems to be mostly mandatory now

upgrade to the latest docker plugin version and use a docker prefix which seems to be mostly mandatory now

---

apps/chaos-monkey/src/main/fabric8/templateParameters.properties

added non blank default for includes to avoid the include pattern being defaulted to `${CHAOS_MONKEY_INCLUDES}` if run from inside the fabric8 console

added non blank default for includes to avoid the include pattern being defaulted to `${CHAOS_MONKEY_INCLUDES}` if run from inside the fabric8 console

---

apps/jenkins/src/main/fabric8/env.properties

add DOMAIN env var to jenkins so we can use it to autodefault the domains for each namespace

add DOMAIN env var to jenkins so we can use it to autodefault the domains for each namespace

---

quickstarts/java/camel-cdi-http/pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi-rest/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

Just an upgrade of Fabric8-version to the latest BOM.
I've changed the version in all projects except karaf4 camel-log :-)
Andrea

Upgrade Fabric8-version to 2.2.21 in quickstarts projects

---

quickstarts/java/camel-cdi-http/README.md

replaced incorrect replication controller reference camel-servlet-quickstart with quickstart-war-camel-servlet

fixed oc scale command example in camel-cdi-http README.md

---

quickstarts/java/camel-cdi-http/pom.xml
quickstarts/java/camel-cdi-rest/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/README.md
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/cxf-cdi/src/main/java/io/fabric8/quickstarts/cxfcdi/ApplicationStarter.java
quickstarts/java/cxf-cdi/src/test/java/io/fabric8/quickstarts/cxfcdi/CrmTest.java
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/pom.xml
quickstarts/java/sandbox-camel-cdi-mq/camel-cdi-mq/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml

fabric8/java-jboss-openjdk8-jdk is now used as base image for the java quickstarts. Cleaned up a bit the properties, too.
Note, that the classpath is now properly created for flat classpath apps. This is done via the maven-dependency-plugin's 'buildClasspath' goal.
Updated to docker-maven-plugin 0.13.5, too.

Changed to d-m-p 0.13.5 and jboss-jdk base image for java quickstarts

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-mainclass/pom.xml

This is needed since when building the current path separator will be used by default which is ';' on Windows and which obviously won't work on Linux.
Please note that we soon switch over to hawt-app for creating the classpath which make this fix obsolete.
Fixes fabric8io/fabric8#4881

Set classpath separator fix to ":" when creating classpath.

---

quickstart/war/wildfly/README.md

This PR resolves #809 
Now docs are aligned with other qs.
This particular qs cannot be run locally, because it was originally thought as an example of scaling.

Resolves #809 Update Wildfly readme for qs

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-fatjar/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

- Use new s2i base images 1.1.1
- Introduce env  AB_JOLOKIA_AUTH_OPENSHIFT which will be use in fabric8 deployment descriptors to switch on OpenShift SSL auth for the proxy.

Update to new base image + fix with openshift auth

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

So that its more stable on the patch level. 1.2 will alway point to the latest patch.

Update base images to 1.2

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-swagger/pom.xml
quickstart/spring-boot/ribbon/pom.xml
quickstart/war/camel-servlet/pom.xml

lets use a ribbon SA for the spring-boot-ribbon quickstart and lets add the service paths to HTTP based quickstarts that don't use / as the entrypoint

lets use a ribbon SA for the spring-boot-ribbon quickstart and lets add the service paths to HTTP based quickstarts that don't use / as the entrypoint

---

quickstart/cdi/cxf/pom.xml

- Include the artifacts of the missing Jackson dependencies required by Swagger
- Add the version number of jackson to the pom file
- Use same version of jackson as supported by Swagger

Add missing Jackson dependencies required by Swagger

---

quickstart/cdi/cxf/pom.xml

- Add missing jackson dataformat yaml jar file required by Swagger (see issue 1251)

Add missing jackson dataformat yaml jar file required by Swagger

---

quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/camel/quickstart-template.json

I think it's time to use the java-s2i image for the spring-boot quickstart. 
This patch fixes the issue with the visualization of the jolokia console (https://github.com/fabric8io/ipaas-quickstarts/issues/956).
I also fixed the template.json file for s2i. According to https://github.com/openshift/origin/issues/3487, tags are not allowed in the "dockerImageRepository" element.
I removed the tag indication and verified that the correct tag is still used (it is referenced in the BuildConfig section).

#956: Switch to java-s2i image, fixed console and s2i build

---

quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/camel/quickstart-template.json

Reverts fabric8io/ipaas-quickstarts#1254

Revert "#956: Switch to java-s2i image, fixed console and s2i build"

---

quickstart/spring-boot/camel-amq/src/main/resources/META-INF/spring/camel-context.xml
quickstart/spring-boot/camel-amq/src/main/resources/data/order1.xml
quickstart/spring-boot/camel-amq/src/main/resources/data/order2.xml
quickstart/spring-boot/camel-amq/src/main/resources/data/order3.xml
quickstart/spring-boot/camel-amq/src/main/resources/data/order4.xml
quickstart/spring-boot/camel-amq/src/main/resources/data/order5.xml

Due to file permission issues on some docker images, I removed the routes-to-files from the camel-amq quickstart. I also fixed sample files to comply with xpath expressions defined in the routes.

Fixed file permission issues for camel-amq quickstart

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel-swagger/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/infinispan/infinispan-client/pom.xml
quickstart/infinispan/infinispan-server/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/fatjar/pom.xml
quickstart/java/mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/spring-boot/camel-amq/pom.xml
quickstart/spring-boot/camel-drools/pom.xml
quickstart/spring-boot/camel-teiid/pom.xml
quickstart/spring-boot/hystrix/pom.xml
quickstart/spring-boot/ribbon/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/vertx/simplest/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
quickstart/wildfly/camel-cdi/pom.xml
quickstart/wildfly/camel-ejb/pom.xml
quickstart/wildfly/camel-jaxrs/pom.xml
quickstart/wildfly/camel-jaxws/pom.xml

lets use fabric8.image instead of docker.image to avoid breaking docker-maven-plugin

lets use fabric8.image instead of docker.image to avoid breaking docker-maven-plugin

---

archetype-builder/src/main/java/io/fabric8/tooling/archetype/builder/CatalogBuilder.java

When a description contains special chars (e.g. `Spring Boot & Red Hat SSO`), the generated XML is not properly escaped

Properly escape archetype description

---

ReadMe.md
archetype-builder/src/main/resources/io/fabric8/tooling/archetype/builder/default-archetype-descriptor.xml

Json files are used in quickstarts to include additional resources in Kubernetes integration tests.

OSFUSE-404: adding json resources in the archetypes
