fabric8io/ipaas-quickstarts

apps/api-registry/pom.xml
apps/app-library/pom.xml
pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/beginner/camel-cbr/pom.xml
quickstarts/karaf/beginner/camel-eips/pom.xml
quickstarts/karaf/beginner/camel-errorhandler/pom.xml
quickstarts/karaf/beginner/camel-log-wiki/pom.xml
quickstarts/karaf/beginner/camel-log/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-dozer-wiki/pom.xml
quickstarts/karaf/camel-drools/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf/camel-cxf-code-first/pom.xml
quickstarts/karaf/cxf/camel-cxf-contract-first/pom.xml
quickstarts/karaf/cxf/rest/pom.xml
quickstarts/karaf/cxf/secure-rest/pom.xml
quickstarts/karaf/cxf/secure-soap/pom.xml
quickstarts/karaf/cxf/soap/pom.xml
quickstarts/karaf/profiles/camel-twitter/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

upgraded jube and fabric8 versions

upgraded jube and fabric8 versions

---

pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/simple-mainclass/pom.xml

upgrade jube

---

apps/app-library/pom.xml

use the right version when releasing and use the latest fixed up version for development

use the right version when releasing and use the latest fixed up version for development

---

apps/console/pom.xml

update the console app defintion to use the new hawtio-kubernetes container

update the console app defintion to use the new hawtio-kubernetes container

---

apps/api-registry/pom.xml
apps/app-library/pom.xml
pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/beginner/camel-cbr/pom.xml
quickstarts/karaf/beginner/camel-eips/pom.xml
quickstarts/karaf/beginner/camel-errorhandler/pom.xml
quickstarts/karaf/beginner/camel-log-wiki/pom.xml
quickstarts/karaf/beginner/camel-log/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-dozer-wiki/pom.xml
quickstarts/karaf/camel-drools/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf/camel-cxf-code-first/pom.xml
quickstarts/karaf/cxf/camel-cxf-contract-first/pom.xml
quickstarts/karaf/cxf/rest/pom.xml
quickstarts/karaf/cxf/secure-rest/pom.xml
quickstarts/karaf/cxf/secure-soap/pom.xml
quickstarts/karaf/cxf/soap/pom.xml
quickstarts/karaf/profiles/camel-twitter/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

upgrade to the new release of fabric8 and jube

upgrade to the new release of fabric8 and jube

---

apps/fabric8-http-gateway/pom.xml

fix build error

---

quickstarts/java/jgroups-greeter/pom.xml

fix release build for jgroups-greeter

fix release build for jgroups-greeter

---

quickstarts/java/jgroups-greeter/pom.xml

another fix on the release build for jgroups-greeter

another fix on the release build for jgroups-greeter

---

apps/api-registry/pom.xml
apps/app-library/pom.xml
pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/beginner/camel-cbr/pom.xml
quickstarts/karaf/beginner/camel-eips/pom.xml
quickstarts/karaf/beginner/camel-errorhandler/pom.xml
quickstarts/karaf/beginner/camel-log-wiki/pom.xml
quickstarts/karaf/beginner/camel-log/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-dozer-wiki/pom.xml
quickstarts/karaf/camel-drools/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf/camel-cxf-code-first/pom.xml
quickstarts/karaf/cxf/camel-cxf-contract-first/pom.xml
quickstarts/karaf/cxf/rest/pom.xml
quickstarts/karaf/cxf/secure-rest/pom.xml
quickstarts/karaf/cxf/secure-soap/pom.xml
quickstarts/karaf/cxf/soap/pom.xml
quickstarts/karaf/profiles/camel-twitter/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

upgraded jube and fabric8

---

apps/api-registry/pom.xml
apps/app-library/pom.xml
pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/beginner/camel-cbr/pom.xml
quickstarts/karaf/beginner/camel-eips/pom.xml
quickstarts/karaf/beginner/camel-errorhandler/pom.xml
quickstarts/karaf/beginner/camel-log-wiki/pom.xml
quickstarts/karaf/beginner/camel-log/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-dozer-wiki/pom.xml
quickstarts/karaf/camel-drools/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf/camel-cxf-code-first/pom.xml
quickstarts/karaf/cxf/camel-cxf-contract-first/pom.xml
quickstarts/karaf/cxf/rest/pom.xml
quickstarts/karaf/cxf/secure-rest/pom.xml
quickstarts/karaf/cxf/secure-soap/pom.xml
quickstarts/karaf/cxf/soap/pom.xml
quickstarts/karaf/profiles/camel-twitter/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

upgraded fabric8 and jube

---

archetypes-catalog/pom.xml
archetypes-catalog/src/main/java/io/fabric8/archetypes/catalog/ArchetypesCatalog.java

attempt to fix the lack of archetype-catalog.xml publication by the release build; lets make a normal jar and see if that helps

attempt to fix the lack of archetype-catalog.xml publication by the release build; lets make a normal jar and see if that helps

---

quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-cdi/src/test/java/io/fabric8/tests/integration/AppKubernetesTest.java
quickstarts/java/camel-cdi/src/test/resources/log4j.properties
quickstarts/java/camel-spring/pom.xml
quickstarts/java/camel-spring/src/test/java/io/fabric8/tests/integration/AppKubernetesTest.java
quickstarts/java/camel-spring/src/test/resources/log4j.properties
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/cxf-cdi/src/test/java/io/fabric8/quickstarts/cxfcdi/AppKubernetesTest.java
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/activemq/src/test/java/io/fabric8/tests/integration/AppKubernetesTest.java
quickstarts/spring-boot/activemq/src/test/resources/log4j.properties
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/camel/src/test/java/io/fabric8/tests/integration/AppKubernetesTest.java
quickstarts/spring-boot/camel/src/test/resources/log4j.properties
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/keycloak/src/test/java/io/fabric8/tests/integration/AppKubernetesTest.java
quickstarts/spring-boot/keycloak/src/test/resources/log4j.properties
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc-ip/src/test/java/io/fabric8/tests/integration/AppKubernetesTest.java
quickstarts/spring-boot/webmvc-ip/src/test/resources/log4j.properties
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/spring-boot/webmvc/src/test/java/io/fabric8/quickstarts/springbootmvc/AppKubernetesTest.java

add a kubernetes integration test to the java/spring boot quickstarts

add a kubernetes integration test to the java/spring boot quickstarts

---

apps/app-library/.gitignore
apps/app-library/pom.xml
apps/app-library/src/main/java/io/fabric8/app/library/Main.java
apps/app-library/src/main/java/io/fabric8/app/library/support/GitContentServlet.java
apps/app-library/src/main/java/io/fabric8/app/library/support/GitServletFacade.java
apps/app-library/src/main/java/io/fabric8/app/library/support/HawtioProducers.java
apps/app-library/src/main/java/io/fabric8/app/library/support/KubernetesService.java
apps/app-library/src/main/java/io/fabric8/app/library/support/KubernetesServiceMXBean.java
apps/app-library/src/main/resources/io/fabric8/app/library/index.html

allow a git clone to be done on the app library

allow a git clone to be done on the app library

---

apps/app-library/src/main/resources/kubernetes-extra.json

lets expose the app library over jolokia for now for the current hawtio-wiki plugin until we migrate to a wiki REST API

lets expose the app library over jolokia for now for the current hawtio-wiki plugin until we migrate to a wiki REST API

---

rest-utils/src/main/java/io/fabric8/rest/utils/Servers.java

add helper function so its easier to just override the default port

add helper function so its easier to just override the default port

---

apps/api-registry/pom.xml
apps/app-library/pom.xml
pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/beginner/camel-cbr/pom.xml
quickstarts/karaf/beginner/camel-eips/pom.xml
quickstarts/karaf/beginner/camel-errorhandler/pom.xml
quickstarts/karaf/beginner/camel-log-wiki/pom.xml
quickstarts/karaf/beginner/camel-log/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-dozer-wiki/pom.xml
quickstarts/karaf/camel-drools/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf/camel-cxf-code-first/pom.xml
quickstarts/karaf/cxf/camel-cxf-contract-first/pom.xml
quickstarts/karaf/cxf/rest/pom.xml
quickstarts/karaf/cxf/secure-rest/pom.xml
quickstarts/karaf/cxf/secure-soap/pom.xml
quickstarts/karaf/cxf/soap/pom.xml
quickstarts/karaf/profiles/camel-twitter/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

upgrade fabric8 and jube

---

apps/pom.xml

renamed modules in alphabetical order and added the missing gogs

renamed modules in alphabetical order and added the missing gogs

---

apps/gogs/src/main/fabric8/kubernetes.json

added ROOT_URL support to gogs

added ROOT_URL support to gogs

---

pom.xml

attempt at fixing the release build

attempt at fixing the release build

---

apps/app-library/src/main/java/io/fabric8/app/library/support/GitContentServlet.java

fixes #3675 so that we add an ETag response header and we check for incoming ETag headers and return a 304 if its the same

fixes #3675 so that we add an ETag response header and we check for incoming ETag headers and return a 304 if its the same

---

apps/api-registry/pom.xml
apps/app-library/pom.xml

avoid bad version

---

quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml

And there is a even newer version

Upgrade to spring boot 1.2.3

---

apps/elasticsearch/pom.xml
apps/gerrit/src/main/fabric8/kubernetes.json
apps/gogs/src/main/fabric8/kubernetes.json
apps/grafana/src/main/fabric8/kubernetes.json
apps/influxdb/pom.xml
apps/kibana/pom.xml
apps/kibana/src/main/fabric8/kubernetes.json
apps/kiwi-irc/src/main/fabric8/kubernetes.json

Remove routes, switch to standard ports, generate rather than hardcode JSON files

---

apps/cdelivery/pom.xml
apps/cdelivery/src/main/java/io/fabric8/cdelivery/RemoteJbpmProducer.java

fix up correct env vars so the cdelivery service works on openshift

fix up correct env vars so the cdelivery service works on openshift

---

apps/brackets/ReadMe.md
apps/brackets/pom.xml
apps/brackets/src/main/fabric8/icon.svg
apps/brackets/src/test/java/io/fabric8/apps/brackets/BracketsKubernetesTest.java
apps/pom.xml

added brackets app

---

apps/cdelivery/pom.xml
apps/hubot-notifier/pom.xml

until we can get secrets to work in openshift 0.4.x lets use an env var to define the namespace to watch for builds

until we can get secrets to work in openshift 0.4.x lets use an env var to define the namespace to watch for builds

---

pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/beginner/camel-cbr/pom.xml
quickstarts/karaf/beginner/camel-eips/pom.xml
quickstarts/karaf/beginner/camel-errorhandler/pom.xml
quickstarts/karaf/beginner/camel-log-wiki/pom.xml
quickstarts/karaf/beginner/camel-log/pom.xml
quickstarts/karaf/camel-dozer-wiki/pom.xml
quickstarts/karaf/camel-drools/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf/camel-cxf-contract-first/pom.xml
quickstarts/karaf/cxf/rest/pom.xml
quickstarts/karaf/cxf/secure-rest/pom.xml
quickstarts/karaf/cxf/soap/pom.xml
quickstarts/karaf/profiles/camel-twitter/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/rest/pom.xml

upgraded jube

---

apps/hubot-notifier/src/main/java/io/fabric8/hubot/notifier/HubotBuildListener.java
apps/orion/pom.xml
apps/pom.xml

added missing app

---

app-groups/cdelivery/pom.xml
app-groups/ipaas/pom.xml
app-groups/kitchen-sink/pom.xml
app-groups/logging/pom.xml
app-groups/management/pom.xml
app-groups/metrics/pom.xml
app-groups/pom.xml
apps/hubot-letschat/src/main/fabric8/kubernetes.json

#3850 create a more modular set of app groups so folks can pick and choose which bits of fabric8 they want

#3850 create a more modular set of app groups so folks can pick and choose which bits of fabric8 they want

---

app-groups/cdelivery/pom.xml
apps/pom.xml

re-enable hubot-letschat now templates are working again

re-enable hubot-letschat now templates are working again

---

apps/gogs/pom.xml
apps/jenkins/pom.xml

add templates for gogs and jenkins so we can configure the gogs domain or the jenkins seed project git repo

add templates for gogs and jenkins so we can configure the gogs domain or the jenkins seed project git repo

---

apps/console/pom.xml
apps/jenkins/pom.xml

lets actually pass in the env var from the template - doh! :)

---

apps/jenkins/pom.xml
apps/sonarqube/src/main/fabric8/kubernetes.json

added a liveness probe to jenkins so that we can ensure we can talk to docker

added a liveness probe to jenkins so that we can ensure we can talk to docker

---

apps/hubot-notifier/pom.xml

add certs to the build watcher

add certs to the build watcher

---

pom.xml

lets try disable the gpg plugin by default unless using the release profile

lets try disable the gpg plugin by default unless using the release profile

---

apps/console/pom.xml

switch to the fabric8/fabric8-console docker image

switch to the fabric8/fabric8-console docker image

---

app-groups/cdelivery-core/pom.xml
app-groups/pom.xml

add a minimal cdelivery core that just includes the console, gogs, nexus, jenkins, sonaqube

add a minimal cdelivery core that just includes the console, gogs, nexus, jenkins, sonaqube

---

apps/apiman-manager-api/pom.xml
apps/apiman-manager-api/src/main/java/io/fabric8/apiman/ManagerApiMicroService.java
apps/apiman-manager-api/src/main/java/io/fabric8/apiman/ManagerApiMicroServiceCdiFactory.java
apps/apiman-manager-api/src/main/java/io/fabric8/apiman/ManagerApiMicroServiceConfig.java
apps/apiman-manager-api/src/main/resources/log4j2.xml
apps/apiman-manager-api/src/test/java/io/fabric8/apiman/ManagerApiConfigTest.java

Also updated tests
Apologies for any PR noise.

Use apiman manager logger

---

app-groups/ReadMe.md
app-groups/base/ReadMe.md
app-groups/cdelivery-core/ReadMe.md
app-groups/cdelivery/ReadMe.md
app-groups/ipaas/ReadMe.md
app-groups/logging/ReadMe.md
app-groups/management/ReadMe.md
app-groups/metrics/ReadMe.md

add some readme files to help folks noodling source via github

add some readme files to help folks noodling source via github

---

pom.xml

upgrade to the latest docker maven plugin

upgrade to the latest docker maven plugin

---

pom.xml

add docker registry property to avoid the release build barfing

add docker registry property to avoid the release build barfing

---

apps/apiman-manager-api/pom.xml
pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/beginner/camel-cbr/pom.xml
quickstarts/karaf/beginner/camel-eips/pom.xml
quickstarts/karaf/beginner/camel-errorhandler/pom.xml
quickstarts/karaf/beginner/camel-log-wiki/pom.xml
quickstarts/karaf/beginner/camel-log/pom.xml
quickstarts/karaf/camel-dozer-wiki/pom.xml
quickstarts/karaf/camel-drools/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf/camel-cxf-contract-first/pom.xml
quickstarts/karaf/cxf/rest/pom.xml
quickstarts/karaf/cxf/secure-rest/pom.xml
quickstarts/karaf/cxf/soap/pom.xml
quickstarts/karaf/profiles/camel-twitter/pom.xml
quickstarts/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/rest/pom.xml

try fix the failing release script for apiman

try fix the failing release script for apiman

---

apps/app-library/pom.xml
apps/app-library/src/main/java/io/fabric8/app/library/support/KubernetesNames.java
apps/fabric8-http-gateway/pom.xml

fix the apps so they can be used on master of fabric8

fix the apps so they can be used on master of fabric8

---

apps/kibana/src/main/fabric8/kubernetes.json

port kibana to v1beta3

---

apps/api-registry/pom.xml
apps/apiman/pom.xml
apps/pom.xml

port to latest snapshot of fabric8

port to latest snapshot of fabric8

---

apps/cdelivery/src/main/java/io/fabric8/cdelivery/BuildSignallerServiceProducer.java
apps/cdelivery/src/main/java/io/fabric8/cdelivery/CDeliveryService.java
apps/hubot-notifier/src/main/java/io/fabric8/hubot/notifier/BuildWatchService.java

fixed up correct service ids

---

apps/jenkins/pom.xml

work around gcc requirement by default now in golang

work around gcc requirement by default now in golang

---

apps/fabric8mq-controller/src/main/resources/META-INF/replicator-template.json
apps/fabric8mq-controller/src/test/resources/META-INF/replicator-template.json
apps/hubot/src/main/fabric8/kubernetes.json
apps/kibana/src/main/fabric8/kubernetes.json
apps/letschat/src/main/fabric8/kubernetes.json
apps/sonarqube/src/main/fabric8/kubernetes.json
apps/taiga/src/main/fabric8/kubernetes.json

fixed broken artifactids

---

apps/app-library/pom.xml
apps/cadvisor/src/main/fabric8/kubernetes.json
apps/fabric8mq-controller/pom.xml
apps/fabric8mq-controller/src/main/resources/META-INF/replicator-template.json
apps/fabric8mq/pom.xml
apps/grafana/src/main/fabric8/kubernetes.json
apps/heapster/src/main/fabric8/kubernetes.json
apps/hubot-notifier/src/main/java/io/fabric8/hubot/notifier/KubernetesHubotNotifier.java
apps/jadvisor/src/main/fabric8/kubernetes.json
apps/keycloak/src/main/fabric8/kubernetes.json
pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

first spike of https://github.com/fabric8io/fabric8/issues/4071 to notify hubot if kubernetes resources change

first spike of https://github.com/fabric8io/fabric8/issues/4071 to notify hubot if kubernetes resources change

---

apps/hubot-notifier/src/main/java/io/fabric8/hubot/notifier/KubernetesHubotNotifier.java

fixed build error on snapshot of fabric8

fixed build error on snapshot of fabric8

---

apps/hubot-notifier/pom.xml

fix release build

---

pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

upgrade to fabric8 2.1.10

---

app-groups/cdelivery/pom.xml
app-groups/ipaas/pom.xml

lets include the create project wizard in the cdelivery app

lets include the create project wizard in the cdelivery app

---

apps/hubot-notifier/pom.xml
apps/hubot-notifier/src/main/fabric8/env.properties

added the certificate env var

---

apps/elasticsearch/pom.xml
apps/infinispan-server/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml

Updated poms to docker-maven-plugin 0.12.0

---

apps/api-registry/src/test/resources/localApiRegistryService.json
apps/app-library/src/test/resources/localApiRegistryService.json
apps/cadvisor/src/main/fabric8/kubernetes.json
apps/fabric8mq-controller/src/main/resources/META-INF/replicator-template.json
apps/fabric8mq-controller/src/test/resources/META-INF/replicator-template.json
apps/fabric8mq/src/main/resources/META-INF/replicator-template.json
apps/hubot/src/main/fabric8/kubernetes.json
apps/infinispan-server/src/main/fabric8/kubernetes.json
apps/jadvisor/src/main/fabric8/kubernetes.json
apps/keycloak/src/main/fabric8/kubernetes.json
apps/letschat/src/main/fabric8/kubernetes.json
apps/sonarqube/src/main/fabric8/kubernetes.json
apps/taiga/src/main/fabric8/kubernetes.json
apps/zookeeper/src/main/fabric8/kubernetes.json
quickstarts/java/jgroups-greeter/src/main/resources/kubernetes.json

updated to kubernetes v1

---

apps/api-registry/pom.xml
apps/app-library/pom.xml
apps/cdelivery/pom.xml
apps/hubot-notifier/pom.xml
pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

update snapshot profile to the 2.3-SNAPSHOT version

update snapshot profile to the 2.3-SNAPSHOT version

---

apps/hubot-notifier/src/main/fabric8/env.properties

enable service accounts for secrets

enable service accounts for secrets

---

apps/hubot-notifier/src/main/fabric8/env.properties
apps/hubot-notifier/src/main/java/io/fabric8/hubot/notifier/KubernetesHubotNotifier.java
apps/hubot-notifier/src/main/java/io/fabric8/hubot/notifier/NotifyConfig.java
apps/hubot-notifier/src/main/resources/jetty-logging.properties

fixes https://github.com/fabric8io/fabric8/issues/4252

fixes https://github.com/fabric8io/fabric8/issues/4252

---

app-groups/apiman/pom.xml
app-groups/ipaas/pom.xml

fixes https://github.com/fabric8io/fabric8/issues/4296 and add apiman into iPaaS

fixes https://github.com/fabric8io/fabric8/issues/4296 and add apiman into iPaaS

---

app-groups/ipaas/pom.xml
app-groups/pom.xml
apps/pom.xml
distro/pom.xml
distro/src/main/assembly/templates.xml
pom.xml
quickstarts/pom.xml

fix up broken icons for app-groups #4301

fix up broken icons for app-groups #4301

---

quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/cxf-cdi/src/main/java/io/fabric8/quickstarts/cxfcdi/ApplicationStarter.java
quickstarts/java/cxf-cdi/src/main/java/io/fabric8/quickstarts/cxfcdi/CxfCdiApplication.java
quickstarts/java/cxf-cdi/src/main/java/io/fabric8/quickstarts/cxfcdi/RootService.java
quickstarts/java/cxf-cdi/src/main/resources/io/fabric8/quickstarts/cxfcdi/index.html

#26 add index.html to cxfcdi

---

pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi-rest/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

fix up hubot-letschat so it can use the login and password to find a token and login to letschat on startup

fix up hubot-letschat so it can use the login and password to find a token and login to letschat on startup

---

pom.xml

upgrade docker maven plugin and remove the docker.registry prefix

upgrade docker maven plugin and remove the docker.registry prefix

---

quickstarts/java/camel-cdi-http/pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi-rest/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

Hi.
This PR fixes #576.
Andrea

Fixes #576 Upgrade Docker Maven Plugin to 0.13.0

---

quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml

Hi.
This PR fixes #580.
Andrea

Fixes #580 Upgrade Spring-boot to version 1.2.5.RELEASE

---

pom.xml

fix typo on property - doh!

---

pom.xml

Hi.
This PR upgrade Maven enforcer plugin to the latest version 1.4
Andrea

Upgrade maven-enforcer-plugin to version 1.4

---

apps/jenkins/pom.xml
quickstarts/java/camel-cdi-http/pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi-rest/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

lets add an env var to the pod ID https://github.com/fabric8io/fabric8/issues/4448

lets add an env var to the pod ID https://github.com/fabric8io/fabric8/issues/4448

---

apps/templates/src/main/java/io/fabric8/templates/TemplatesService.java

fixes https://github.com/fabric8io/fabric8/issues/4468 after bad string being returned by accident ;)

fixes https://github.com/fabric8io/fabric8/issues/4468 after bad string being returned by accident ;)

---

app-groups/console-kubernetes/ReadMe.md
app-groups/console-kubernetes/pom.xml
app-groups/pom.xml
apps/fabric8/src/main/fabric8/env.properties
apps/fabric8/src/main/fabric8/templateParameters.properties

fixes https://github.com/fabric8io/fabric8/issues/4479

fixes https://github.com/fabric8io/fabric8/issues/4479

---

apps/templates/pom.xml
apps/templates/src/main/java/io/fabric8/templates/TemplatesService.java

https://github.com/fabric8io/fabric8/issues/4468 prepopulate the templates with the default apps for fabric8

https://github.com/fabric8io/fabric8/issues/4468 prepopulate the templates with the default apps for fabric8

---

apps/fabric8/src/main/fabric8/env.properties
apps/fabric8/src/main/fabric8/templateParameters.properties

fixes #4485

---

pom.xml
quickstarts/java/camel-cdi-http/pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi-rest/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

upgraded fabric8 version

---

apps/hubot-letschat/src/main/java/io/fabric8/apps/hubot/letschat/HubotLetschatModelProcessor.java

fix typo on service name

---

quickstarts/java/camel-cdi-http/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/java/camel-cdi-mq/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/java/camel-cdi-rest/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/java/camel-cdi/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/java/camel-spring/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/java/cxf-cdi/src/test/java/io/fabric8/quickstarts/cxfcdi/KubernetesIntegrationKT.java
quickstarts/spring-boot/activemq/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/spring-boot/camel/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/spring-boot/keycloak/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/spring-boot/webmvc-ip/src/test/java/io/fabric8/tests/integration/KubernetesIntegrationKT.java
quickstarts/spring-boot/webmvc/src/test/java/io/fabric8/quickstarts/springbootmvc/KubernetesIntegrationKT.java

fixes https://github.com/fabric8io/fabric8/issues/4524

fixes https://github.com/fabric8io/fabric8/issues/4524

---

apps/chaos-monkey/pom.xml
apps/fabric8-forge/pom.xml
apps/fabric8-http-gateway/pom.xml
apps/fabric8mq/pom.xml
apps/hubot-notifier/pom.xml
apps/jenkins/pom.xml

remove the secrets which are no longer required now we have service accounts

remove the secrets which are no longer required now we have service accounts

---

pom.xml
quickstarts/java/camel-cdi-http/pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi-rest/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml

Upgrade Docker Maven plugin to version 0.13.2
Andrea

Upgrade Docker Maven Plugin to version 0.13.2

---

quickstarts/war/wildfly/README.md
quickstarts/war/wildfly/pom.xml
quickstarts/war/wildfly/src/main/java/io/fabric8/wildfly/ExampleServlet.java
quickstarts/war/wildfly/src/main/java/io/fabric8/wildfly/GreetingApplication.java
quickstarts/war/wildfly/src/main/java/io/fabric8/wildfly/GreetingResource.java
quickstarts/war/wildfly/src/main/webapp/WEB-INF/jboss-web.xml
quickstarts/war/wildfly/test-script.sh

Hi,
This PR is related to #647 
Andrea

Resolves #647 Add a Wildfly-quickstart example

---

quickstarts/war/README.md
quickstarts/war/pom.xml
quickstarts/war/wildfly/pom.xml

I forget to add the module to parent pom and name and description on quickstart-wildfly pom.xml
Sorry. 
Andrea

Related to #647 Forget to add module and name and description in pom.xml

---

pom.xml
quickstarts/java/camel-cdi-http/pom.xml
quickstarts/java/camel-cdi-mq/pom.xml
quickstarts/java/camel-cdi-rest/pom.xml
quickstarts/java/camel-cdi/pom.xml
quickstarts/java/camel-spring/pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/jgroups-greeter/pom.xml
quickstarts/java/simple-fatjar/pom.xml
quickstarts/java/simple-mainclass/pom.xml
quickstarts/karaf/camel-amq/pom.xml
quickstarts/karaf/camel-log/pom.xml
quickstarts/karaf/camel-rest-sql/pom.xml
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/karaf4/camel-log/pom.xml
quickstarts/pom.xml
quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml
quickstarts/war/camel-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/rest/pom.xml
quickstarts/war/wildfly/pom.xml

Upgrade Docker Maven Plugin to version 0.13.3
Andrea

Upgrade to Docker Maven Plugin 0.13.3

---

quickstarts/spring-boot/activemq/pom.xml
quickstarts/spring-boot/camel/pom.xml
quickstarts/spring-boot/keycloak/pom.xml
quickstarts/spring-boot/webmvc-ip/pom.xml
quickstarts/spring-boot/webmvc/pom.xml

Upgrade Spring-boot to version 1.2.6.RELEASE
Andrea

Upgrade Spring-boot to version 1.2.6.RELEASE

---

pom.xml
quickstarts/java/cxf-cdi/pom.xml
quickstarts/java/cxf-cdi/src/main/java/io/fabric8/quickstarts/cxfcdi/CustomerService.java
quickstarts/java/cxf-cdi/src/main/java/io/fabric8/quickstarts/cxfcdi/CxfCdiApplication.java
quickstarts/java/cxf-cdi/src/main/java/io/fabric8/quickstarts/cxfcdi/RootService.java
quickstarts/karaf/cxf-rest/pom.xml
quickstarts/karaf/cxf-rest/src/main/java/io/fabric8/quickstarts/rest/CustomerService.java
quickstarts/pom.xml
quickstarts/war/cxf-cdi-servlet/pom.xml
quickstarts/war/cxf-cdi-servlet/src/main/java/io/fabric8/quickstarts/cxfcdi/CustomerService.java

Also using Project-Attributes in the Manifest to populate the info section in the swagger document.

Upgrading io.swagger to 1.5.3 to support Swagger 2.0

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-rest/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-fatjar/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/camel-cdi-mq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

This makes dockerhub handling much easier for now until we change from automatic builds to manual builds.

Changed jboss-java base image to latest

---

quickstart/cdi/camel-cdi-mq/pom.xml
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-mainclass/pom.xml

Reintroduce container port exposure for 8778

---

pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/quickstarts/activemq/pom.xml

Just an alignment of Docker Maven Plugin version in all the projects.
Andrea

Aligned Docker Maven Plugin version to 0.13.5 in all the projects

---

pom.xml

Upgrade Arquillian to version 1.1.9.Final
Andrea

Upgrade Arquillian to version 1.1.9.Final

---

pom.xml
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/README.md
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-fatjar/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

- Update to hawt-app plugin for generating the images
- Removed progiles 'docker-build' and 'docker-push'. Use goals directly instead.

Update to hawt-app & removed unneeded profiles

---

quickstart/cdi/camel-http/README.md
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-fatjar/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/war/wildfly/pom.xml

Default sample commands:
* mvn -Pf8-build         ... build Docker images and create OpenShift deployment configs
* mvn -Pf8-deploy        ... f8-build + push to Docker registry + applying deployment config to OpenShift
* mvn -Pf8-local-deploy ... deployment for a single node setup without pushing to a registry

Added simplifying profiles

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

Streamlined target output directory

Update to new base image location

---

pom.xml

Upgrade Maven Exec Plugin to version 1.4.0
Andrea

Upgrade Maven Exec Plugin to version 1.4.0

---

pom.xml

Upgrade Maven Enforcer Plugin to version 1.4.1
Andrea

Upgrade Maven Enforcer Plugin to version 1.4.1

---

pom.xml

Upgrade Arquillian to version 1.1.10.Final
Andrea

Upgrade Arquillian to version 1.1.10.Final

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-fatjar/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml

Should be re-enabled when OpenShift Origin 1.0.7 is out.

Comment out authorization for OpenShift for now

---

quickstart/war/wildfly/README.md
quickstart/war/wildfly/pom.xml

Upgrade the version inside Wildfly Quickstart.
Andrea

Upgrade Wildfly to version 9.0.2.Final in related quickstart

---

quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-amq/src/main/resources/OSGI-INF/blueprint/camel-context.xml
quickstart/karaf/pom.xml

Conflicts:
quickstart/karaf/camel-amq/pom.xml

OSFUSE-106: Fixed camel-amq to use new karaf maven plugin

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-http/quickstart-template.json
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-jetty/quickstart-template.json
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel-mq/quickstart-template.json
quickstart/cdi/camel/pom.xml
quickstart/cdi/camel/quickstart-template.json
quickstart/cdi/cxf/pom.xml
quickstart/cdi/cxf/quickstart-template.json
quickstart/java/camel-spring/pom.xml
quickstart/java/camel-spring/quickstart-template.json
quickstart/java/simple-fatjar/quickstart-template.json
quickstart/java/simple-mainclass/pom.xml
quickstart/java/simple-mainclass/quickstart-template.json
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-amq/quickstart-template.json
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-log/quickstart-template.json
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/camel-rest-sql/quickstart-template.json
quickstart/karaf/cxf-rest/pom.xml
quickstart/karaf/cxf-rest/quickstart-template.json
quickstart/spring-boot/camel/quickstart-template.json
quickstart/spring-boot/webmvc/quickstart-template.json
quickstart/war/camel-servlet/quickstart-template.json
quickstart/war/cxf-cdi-servlet/quickstart-template.json
quickstart/war/wildfly/quickstart-template.json

updated quickstart-templates.json, too.

OSFUSE-173: Update docker base image to the final version of OSBS imgs

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-http/quickstart-template.json
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-jetty/quickstart-template.json
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel-mq/quickstart-template.json
quickstart/cdi/camel/pom.xml
quickstart/cdi/camel/quickstart-template.json
quickstart/cdi/cxf/pom.xml
quickstart/cdi/cxf/quickstart-template.json
quickstart/java/camel-spring/pom.xml
quickstart/java/camel-spring/quickstart-template.json
quickstart/java/simple-fatjar/quickstart-template.json
quickstart/java/simple-mainclass/pom.xml
quickstart/java/simple-mainclass/quickstart-template.json
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-amq/quickstart-template.json
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-log/quickstart-template.json
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/camel-rest-sql/quickstart-template.json
quickstart/karaf/cxf-rest/pom.xml
quickstart/karaf/cxf-rest/quickstart-template.json
quickstart/spring-boot/camel/quickstart-template.json
quickstart/spring-boot/webmvc/quickstart-template.json
quickstart/war/camel-servlet/quickstart-template.json
quickstart/war/cxf-cdi-servlet/quickstart-template.json
quickstart/war/wildfly/quickstart-template.json

This should make things more robust and decoupled (a build number at the end is the freedom for doing dependent artifact agnostic updates)

OSFUSE-173: Change version from 1.0-10 to 1.0

---

pom.xml
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-fatjar/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

Upgrade Docker Maven plugin to version 0.13.7.
Related to: https://github.com/fabric8io/fabric8/issues/5402
Andrea

Upgrade Docker Maven plugin to version 0.13.7

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml

Upgrade Weld to version 2.3.2.Final
Related to: https://github.com/fabric8io/fabric8/issues/5436
Andrea

Resolves #5436 Upgrade Weld to version 2.3.2.Final

---

pom.xml
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-fatjar/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

Resolves #1032 go back to d-m-p 0.13.6 as 0.13.7 cannot redeploy

---

quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/simple-mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

This could help for #1024, #1012 and #956

Update to base images version 1.2.8

---

quickstart/war/wildfly/src/main/java/io/fabric8/wildfly/ExampleServlet.java

Resolves #1070 Wildfly quickstart link to get greeting doesn't work

---

quickstart/war/wildfly/test-script.sh

The test-script bash script mus be aligned too

Related to #1070, the test-script must be updated too

---

quickstart/vertx/pom.xml
quickstart/vertx/simplest/pom.xml
quickstart/vertx/simplest/src/main/java/io/vertx/example/HelloWorldEmbedded.java

Not quite working yet, but something for James to take a butchers at:
@jstrachan

Basic Vert.x quickstart

---

quickstart/vertx/simplest/pom.xml

lets create an external load balancer for the service and use the fat jar

lets create an external load balancer for the service and use the fat jar

---

archetypes-catalog/pom.xml

lets try use the package phase to see if this properly releases the archetypes catalog

lets try use the package phase to see if this properly releases the archetypes catalog

---

archetype-builder/src/main/java/io/fabric8/tooling/archetype/builder/ArchetypeBuilder.java

added the new archetypes to the catalog

added the new archetypes to the catalog

---

pom.xml

Upgrade Arquillian to version 1.1.11.Final
Andrea

Upgrade Arquillian to version 1.1.11.Final

---

pom.xml
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel-swagger/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/fatjar/pom.xml
quickstart/java/mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/spring/camel/pom.xml
quickstart/vertx/simplest/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

Upgrade to latest Docker-maven-plugin 0.13.9
Andrea

Upgrade Docker-maven-plugin to version 0.13.9

---

pom.xml
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel-swagger/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/java/fatjar/pom.xml
quickstart/java/mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/spring/camel/pom.xml
quickstart/vertx/simplest/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/apps/app-library/pom.xml
sandbox/apps/fabric8mq-autoscaler/pom.xml
sandbox/apps/fabric8mq-controller/pom.xml
sandbox/apps/infinispan-server/pom.xml
sandbox/apps/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

Upgrade to new Docker-maven-plugin 0.14.1 with groupId io.fabric8
Andrea

Upgrade to Docker-maven-plugin 0.14.1 with new groupId io.fabric8

---

pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-log/src/main/resources/OSGI-INF/blueprint/camel-log.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/karaf/pom.xml

Fixes up karaf builds so that they get properly signed during release.

---

quickstart/war/wildfly/pom.xml

This PR is related to #1164 
Andrea

Resolves #1164 Upgrade wildfly to v10

---

archetype-itests/pom.xml
quickstart/spring-boot/ribbon/pom.xml

fix the release process

---

quickstart/infinispan/infinispan-client/ReadMe.md
quickstart/infinispan/infinispan-client/pom.xml
quickstart/infinispan/infinispan-client/quickstart-template.json
quickstart/infinispan/infinispan-client/src/main/java/io/fabric8/example/camel/infinispan/routes/CheckValueRoute.java
quickstart/infinispan/infinispan-client/src/main/resources/META-INF/spring/camel-context.xml
quickstart/infinispan/infinispan-client/src/main/resources/log4j.properties
quickstart/infinispan/infinispan-client/src/test/java/io/fabric8/KubernetesIntegrationKT.java
quickstart/infinispan/infinispan-client/src/test/resources/log4j.properties
quickstart/infinispan/infinispan-server/README.md
quickstart/infinispan/infinispan-server/pom.xml
quickstart/infinispan/infinispan-server/quickstart-template.json
quickstart/infinispan/pom.xml
quickstart/pom.xml

This is just the first spike, need some work.
Let me know what do you think about guys :-)

First spike #1203 Infinispan client/server App as quickstart

---

quickstart/infinispan/infinispan-client/pom.xml
quickstart/infinispan/infinispan-client/src/main/resources/META-INF/spring/camel-context.xml
quickstart/infinispan/infinispan-server/pom.xml

Infinispan demo 1203 cont

---

pom.xml
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel-swagger/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/infinispan/infinispan-client/pom.xml
quickstart/infinispan/infinispan-server/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/fatjar/pom.xml
quickstart/java/mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/hystrix/pom.xml
quickstart/spring-boot/ribbon/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/vertx/simplest/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

Upgrade to latest fabric8 version 2.2.105.
Andrea

Upgrade to latest fabric8 release 2.2.105

---

quickstart/karaf/camel-amq/pom.xml

Fixed extension from .tar.gz to .zip

---

pom.xml
quickstart/cdi/camel-http/pom.xml
quickstart/cdi/camel-jetty/pom.xml
quickstart/cdi/camel-mq/pom.xml
quickstart/cdi/camel-swagger/pom.xml
quickstart/cdi/camel/pom.xml
quickstart/cdi/cxf/pom.xml
quickstart/infinispan/infinispan-client/pom.xml
quickstart/infinispan/infinispan-server/pom.xml
quickstart/java/camel-spring/pom.xml
quickstart/java/fatjar/pom.xml
quickstart/java/mainclass/pom.xml
quickstart/karaf/camel-amq/pom.xml
quickstart/karaf/camel-log/pom.xml
quickstart/karaf/camel-rest-sql/pom.xml
quickstart/karaf/cxf-rest/pom.xml
quickstart/pom.xml
quickstart/spring-boot/camel/pom.xml
quickstart/spring-boot/hystrix/pom.xml
quickstart/spring-boot/ribbon/pom.xml
quickstart/spring-boot/webmvc/pom.xml
quickstart/vertx/simplest/pom.xml
quickstart/war/camel-servlet/pom.xml
quickstart/war/cxf-cdi-servlet/pom.xml
quickstart/war/wildfly/pom.xml
sandbox/quickstarts/activemq/pom.xml
sandbox/quickstarts/jgroups-greeter/pom.xml
sandbox/quickstarts/keycloak/pom.xml

Upgrade Docker images, upgrade d-m-p

---

pom.xml
quickstart/cdi/cxf/pom.xml

upgraded fabric8 and fixed up the dependencies of cdi-cxf to avoid clashes with swagger/jackson/fabric8-arquillian

upgraded fabric8 and fixed up the dependencies of cdi-cxf to avoid clashes with swagger/jackson/fabric8-arquillian

---

pom.xml
quickstart/cdi/camel-jetty/pom.xml

migrate to latest fabric8

---

archetype-itests/src/test/java/io/fabric8/tooling/archetype/generator/ArchetypeTest.java

fix validation errors in the itests

fix validation errors in the itests

---

quickstart/cdi/cxf/README.md

- Solve issue 1268. Fix #1268 
- Change content type from text/xml to application/xml
- Replace localhost address with route address
- Add a remark concerning the default namespace

Solve issue 1268

---

quickstart/cdi/cxf/pom.xml
quickstart/cdi/cxf/src/main/resources/log4j.properties

- Remove test scope for slf4j-log4j12 artifact
- Change Logger level to INFO
- Fix #1270

Remove test scope and change Logger level to INFO.

---

pom.xml
quickstart/java/camel-spring/pom.xml
sandbox/apps/cadvisor/src/test/java/io/fabric8/apps/cadvisor/CadvisorKubernetesTest.java
sandbox/apps/fabric8mq-autoscaler/src/test/java/io/fabric8/apps/mq/autoscaler/MQAutoscalerKubernetesTest.java
sandbox/apps/fabric8mq-controller/src/test/java/io/fabric8/apps/mq/MQKubernetesTest.java
sandbox/apps/grafana/src/test/java/io/fabric8/apps/grafana/GrafanaKubernetesTest.java
sandbox/apps/influxdb/src/test/java/io/fabric8/apps/influxdb/InfluxDBKubernetesTest.java
sandbox/apps/jadvisor/src/test/java/io/fabric8/apps/jadvisor/JadvisorKubernetesTest.java
sandbox/apps/jbpm-designer/src/test/java/io/fabric8/apps/jbpm/designer/JbpmDesignerKubernetesTest.java
sandbox/apps/registry/src/test/java/io/fabric8/apps/registry/RegistryKubernetesTest.java

upgrade fabric8

---

archetype-itests/pom.xml

avoid breaking itest

---

archetype-builder/src/main/java/io/fabric8/tooling/archetype/builder/ArchetypeBuilder.java
archetype-builder/src/main/java/io/fabric8/tooling/archetype/builder/Main.java

lets add instructions on how to add missing archetypes to the project

lets add instructions on how to add missing archetypes to the project

---

ReadMe.md
archetype-itests/ReadMe.md
archetype-itests/pom.xml
archetype-itests/src/test/java/io/fabric8/tooling/archetype/generator/ArchetypeTest.java

allow the fabric8.mode to be specified when running the system tests

---

archetype-builder/src/main/java/io/fabric8/tooling/archetype/builder/ArchetypeBuilder.java

This allows better extensibility for the ArchetypeBuilder class

Changing private methods to protected + deleted unused method

---

archetype-builder/pom.xml
archetype-builder/src/main/java/io/fabric8/tooling/archetype/builder/CatalogBuilder.java

https://issues.jboss.org/browse/ENTESB-9892
Thanks!

[ENTESB-9892] Update jackson-databind
